### ISSUE TITLE
Adding data elements to datasets don't work

### ISSUE THREAD

**Issue by ngermeau** [BLSQ/dhis2#39]
I'm in dhis2 2.25 and this is not working and I don't receive any errors. 

```ruby
def add_to_dataset(name, dataset_id,postfix)
  name = "#{name} #{postfix}"
  data_element = $dhis.data_elements.find_by(name: name)
  data_set = $dhis.data_sets.find(dataset_id)
  status = data_set.add_relation(:dataSetElements, data_element.id)
  puts status.inspect
end
`

**Comment by mestachs** [comment]
https://play.dhis2.org/demo/api/dataSets/lyLU2wR22tC vs 
https://play.dhis2.org/release2/api/dataSets/lyLU2wR22tC

since 2.25 version there's a dataSetElement (that can have categorycomboid), the best way I found currently is add a dataSetElement in memory than call the save/update method on the dataset (and
load the dataset with all fields if he have a check if he has a
